name: Custom Vanilla Desktop
id: custom
vibversion: 1.0.7

stages:
  - id: build
    base: ghcr.io/vanilla-os/desktop:main
    addincludes: true
    modules:
      - name: init-setup
        type: shell
        commands:
          - lpkg --unlock
          - apt-get update
          - apt-get install -y curl ca-certificates

      - name: install-tailscale
        type: apt
        sources:
          - key: https://tailscale.com
            uris: https://tailscale.com
            suites: sid
            components: main
        packages:
          - tailscale

      - name: set-image-name-abroot
        type: includes
        includes:
          - modules/80-set-image-abroot-config.yml

      - name: cleanup
        type: shell
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock
